// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// trust wallet core
class TWAnySigner_1 {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  TWAnySigner_1(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  TWAnySigner_1.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// Signs a transaction.
  ffi.Pointer<ffi.Int32> TWAnySignerSign(
    ffi.Pointer<ffi.Int32> input,
    int coin,
  ) {
    return _TWAnySignerSign(
      input,
      coin,
    );
  }

  late final _TWAnySignerSign_ptr =
      _lookup<ffi.NativeFunction<_c_TWAnySignerSign>>('TWAnySignerSign');
  late final _dart_TWAnySignerSign _TWAnySignerSign =
      _TWAnySignerSign_ptr.asFunction<_dart_TWAnySignerSign>();

  /// Signs a json transaction with private key.
  ffi.Pointer<ffi.Int32> TWAnySignerSignJSON(
    ffi.Pointer<ffi.Int32> json,
    ffi.Pointer<ffi.Int32> key,
    int coin,
  ) {
    return _TWAnySignerSignJSON(
      json,
      key,
      coin,
    );
  }

  late final _TWAnySignerSignJSON_ptr =
      _lookup<ffi.NativeFunction<_c_TWAnySignerSignJSON>>(
          'TWAnySignerSignJSON');
  late final _dart_TWAnySignerSignJSON _TWAnySignerSignJSON =
      _TWAnySignerSignJSON_ptr.asFunction<_dart_TWAnySignerSignJSON>();

  int TWAnySignerSupportsJSON(
    int coin,
  ) {
    return _TWAnySignerSupportsJSON(
      coin,
    );
  }

  late final _TWAnySignerSupportsJSON_ptr =
      _lookup<ffi.NativeFunction<_c_TWAnySignerSupportsJSON>>(
          'TWAnySignerSupportsJSON');
  late final _dart_TWAnySignerSupportsJSON _TWAnySignerSupportsJSON =
      _TWAnySignerSupportsJSON_ptr.asFunction<_dart_TWAnySignerSupportsJSON>();

  /// Plan a transaction (for UTXO chains).
  ffi.Pointer<ffi.Int32> TWAnySignerPlan(
    ffi.Pointer<ffi.Int32> input,
    int coin,
  ) {
    return _TWAnySignerPlan(
      input,
      coin,
    );
  }

  late final _TWAnySignerPlan_ptr =
      _lookup<ffi.NativeFunction<_c_TWAnySignerPlan>>('TWAnySignerPlan');
  late final _dart_TWAnySignerPlan _TWAnySignerPlan =
      _TWAnySignerPlan_ptr.asFunction<_dart_TWAnySignerPlan>();
}

/// Helper class to sign any transactions.
class TWAnySigner extends ffi.Opaque {}

typedef _c_TWAnySignerSign = ffi.Pointer<ffi.Int32> Function(
  ffi.Pointer<ffi.Int32> input,
  ffi.Int32 coin,
);

typedef _dart_TWAnySignerSign = ffi.Pointer<ffi.Int32> Function(
  ffi.Pointer<ffi.Int32> input,
  int coin,
);

typedef _c_TWAnySignerSignJSON = ffi.Pointer<ffi.Int32> Function(
  ffi.Pointer<ffi.Int32> json,
  ffi.Pointer<ffi.Int32> key,
  ffi.Int32 coin,
);

typedef _dart_TWAnySignerSignJSON = ffi.Pointer<ffi.Int32> Function(
  ffi.Pointer<ffi.Int32> json,
  ffi.Pointer<ffi.Int32> key,
  int coin,
);

typedef _c_TWAnySignerSupportsJSON = ffi.Int32 Function(
  ffi.Int32 coin,
);

typedef _dart_TWAnySignerSupportsJSON = int Function(
  int coin,
);

typedef _c_TWAnySignerPlan = ffi.Pointer<ffi.Int32> Function(
  ffi.Pointer<ffi.Int32> input,
  ffi.Int32 coin,
);

typedef _dart_TWAnySignerPlan = ffi.Pointer<ffi.Int32> Function(
  ffi.Pointer<ffi.Int32> input,
  int coin,
);
