// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// trust wallet core
class TWData {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  TWData(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  TWData.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// Creates a block of data from a byte array.
  ffi.Pointer<ffi.Void> TWDataCreateWithBytes(
    ffi.Pointer<ffi.Int32> bytes,
    int size,
  ) {
    return _TWDataCreateWithBytes(
      bytes,
      size,
    );
  }

  late final _TWDataCreateWithBytes_ptr =
      _lookup<ffi.NativeFunction<_c_TWDataCreateWithBytes>>(
          'TWDataCreateWithBytes');
  late final _dart_TWDataCreateWithBytes _TWDataCreateWithBytes =
      _TWDataCreateWithBytes_ptr.asFunction<_dart_TWDataCreateWithBytes>();

  /// Creates an uninitialized block of data with the provided size.
  ffi.Pointer<ffi.Void> TWDataCreateWithSize(
    int size,
  ) {
    return _TWDataCreateWithSize(
      size,
    );
  }

  late final _TWDataCreateWithSize_ptr =
      _lookup<ffi.NativeFunction<_c_TWDataCreateWithSize>>(
          'TWDataCreateWithSize');
  late final _dart_TWDataCreateWithSize _TWDataCreateWithSize =
      _TWDataCreateWithSize_ptr.asFunction<_dart_TWDataCreateWithSize>();

  /// Creates a block of data by copying another block of data.
  ffi.Pointer<ffi.Void> TWDataCreateWithData(
    ffi.Pointer<ffi.Void> data,
  ) {
    return _TWDataCreateWithData(
      data,
    );
  }

  late final _TWDataCreateWithData_ptr =
      _lookup<ffi.NativeFunction<_c_TWDataCreateWithData>>(
          'TWDataCreateWithData');
  late final _dart_TWDataCreateWithData _TWDataCreateWithData =
      _TWDataCreateWithData_ptr.asFunction<_dart_TWDataCreateWithData>();

  /// Creates a block of data from a hexadecimal string.  Odd length is invalid (intended grouping to bytes is not obvious).
  ffi.Pointer<ffi.Void> TWDataCreateWithHexString(
    ffi.Pointer<ffi.Int32> hex,
  ) {
    return _TWDataCreateWithHexString(
      hex,
    );
  }

  late final _TWDataCreateWithHexString_ptr =
      _lookup<ffi.NativeFunction<_c_TWDataCreateWithHexString>>(
          'TWDataCreateWithHexString');
  late final _dart_TWDataCreateWithHexString _TWDataCreateWithHexString =
      _TWDataCreateWithHexString_ptr.asFunction<
          _dart_TWDataCreateWithHexString>();

  /// Returns the size in bytes.
  int TWDataSize(
    ffi.Pointer<ffi.Void> data,
  ) {
    return _TWDataSize(
      data,
    );
  }

  late final _TWDataSize_ptr =
      _lookup<ffi.NativeFunction<_c_TWDataSize>>('TWDataSize');
  late final _dart_TWDataSize _TWDataSize =
      _TWDataSize_ptr.asFunction<_dart_TWDataSize>();

  /// Returns the raw pointer to the contents of data.
  ffi.Pointer<ffi.Int32> TWDataBytes(
    ffi.Pointer<ffi.Void> data,
  ) {
    return _TWDataBytes(
      data,
    );
  }

  late final _TWDataBytes_ptr =
      _lookup<ffi.NativeFunction<_c_TWDataBytes>>('TWDataBytes');
  late final _dart_TWDataBytes _TWDataBytes =
      _TWDataBytes_ptr.asFunction<_dart_TWDataBytes>();

  /// Returns the byte at the provided index.
  int TWDataGet(
    ffi.Pointer<ffi.Void> data,
    int index,
  ) {
    return _TWDataGet(
      data,
      index,
    );
  }

  late final _TWDataGet_ptr =
      _lookup<ffi.NativeFunction<_c_TWDataGet>>('TWDataGet');
  late final _dart_TWDataGet _TWDataGet =
      _TWDataGet_ptr.asFunction<_dart_TWDataGet>();

  /// Sets the byte at the provided index.
  void TWDataSet(
    ffi.Pointer<ffi.Void> data,
    int index,
    int byte,
  ) {
    return _TWDataSet(
      data,
      index,
      byte,
    );
  }

  late final _TWDataSet_ptr =
      _lookup<ffi.NativeFunction<_c_TWDataSet>>('TWDataSet');
  late final _dart_TWDataSet _TWDataSet =
      _TWDataSet_ptr.asFunction<_dart_TWDataSet>();

  /// Copies a range of bytes into the provided buffer.
  void TWDataCopyBytes(
    ffi.Pointer<ffi.Void> data,
    int start,
    int size,
    ffi.Pointer<ffi.Int32> output,
  ) {
    return _TWDataCopyBytes(
      data,
      start,
      size,
      output,
    );
  }

  late final _TWDataCopyBytes_ptr =
      _lookup<ffi.NativeFunction<_c_TWDataCopyBytes>>('TWDataCopyBytes');
  late final _dart_TWDataCopyBytes _TWDataCopyBytes =
      _TWDataCopyBytes_ptr.asFunction<_dart_TWDataCopyBytes>();

  /// Replaces a range of bytes with the contents of the provided buffer.
  void TWDataReplaceBytes(
    ffi.Pointer<ffi.Void> data,
    int start,
    int size,
    ffi.Pointer<ffi.Int32> bytes,
  ) {
    return _TWDataReplaceBytes(
      data,
      start,
      size,
      bytes,
    );
  }

  late final _TWDataReplaceBytes_ptr =
      _lookup<ffi.NativeFunction<_c_TWDataReplaceBytes>>('TWDataReplaceBytes');
  late final _dart_TWDataReplaceBytes _TWDataReplaceBytes =
      _TWDataReplaceBytes_ptr.asFunction<_dart_TWDataReplaceBytes>();

  /// Appends data from a byte array.
  void TWDataAppendBytes(
    ffi.Pointer<ffi.Void> data,
    ffi.Pointer<ffi.Int32> bytes,
    int size,
  ) {
    return _TWDataAppendBytes(
      data,
      bytes,
      size,
    );
  }

  late final _TWDataAppendBytes_ptr =
      _lookup<ffi.NativeFunction<_c_TWDataAppendBytes>>('TWDataAppendBytes');
  late final _dart_TWDataAppendBytes _TWDataAppendBytes =
      _TWDataAppendBytes_ptr.asFunction<_dart_TWDataAppendBytes>();

  /// Appends a single byte.
  void TWDataAppendByte(
    ffi.Pointer<ffi.Void> data,
    int byte,
  ) {
    return _TWDataAppendByte(
      data,
      byte,
    );
  }

  late final _TWDataAppendByte_ptr =
      _lookup<ffi.NativeFunction<_c_TWDataAppendByte>>('TWDataAppendByte');
  late final _dart_TWDataAppendByte _TWDataAppendByte =
      _TWDataAppendByte_ptr.asFunction<_dart_TWDataAppendByte>();

  /// Appends a block of data.
  void TWDataAppendData(
    ffi.Pointer<ffi.Void> data,
    ffi.Pointer<ffi.Void> append,
  ) {
    return _TWDataAppendData(
      data,
      append,
    );
  }

  late final _TWDataAppendData_ptr =
      _lookup<ffi.NativeFunction<_c_TWDataAppendData>>('TWDataAppendData');
  late final _dart_TWDataAppendData _TWDataAppendData =
      _TWDataAppendData_ptr.asFunction<_dart_TWDataAppendData>();

  /// Revereses the bytes.
  void TWDataReverse(
    ffi.Pointer<ffi.Void> data,
  ) {
    return _TWDataReverse(
      data,
    );
  }

  late final _TWDataReverse_ptr =
      _lookup<ffi.NativeFunction<_c_TWDataReverse>>('TWDataReverse');
  late final _dart_TWDataReverse _TWDataReverse =
      _TWDataReverse_ptr.asFunction<_dart_TWDataReverse>();

  /// Sets all bytes to the given value.
  void TWDataReset(
    ffi.Pointer<ffi.Void> data,
  ) {
    return _TWDataReset(
      data,
    );
  }

  late final _TWDataReset_ptr =
      _lookup<ffi.NativeFunction<_c_TWDataReset>>('TWDataReset');
  late final _dart_TWDataReset _TWDataReset =
      _TWDataReset_ptr.asFunction<_dart_TWDataReset>();

  /// Deletes a block of data created with a `TWDataCreate*` method.
  void TWDataDelete(
    ffi.Pointer<ffi.Void> data,
  ) {
    return _TWDataDelete(
      data,
    );
  }

  late final _TWDataDelete_ptr =
      _lookup<ffi.NativeFunction<_c_TWDataDelete>>('TWDataDelete');
  late final _dart_TWDataDelete _TWDataDelete =
      _TWDataDelete_ptr.asFunction<_dart_TWDataDelete>();

  /// Determines whether two data blocks are equal.
  int TWDataEqual(
    ffi.Pointer<ffi.Void> lhs,
    ffi.Pointer<ffi.Void> rhs,
  ) {
    return _TWDataEqual(
      lhs,
      rhs,
    );
  }

  late final _TWDataEqual_ptr =
      _lookup<ffi.NativeFunction<_c_TWDataEqual>>('TWDataEqual');
  late final _dart_TWDataEqual _TWDataEqual =
      _TWDataEqual_ptr.asFunction<_dart_TWDataEqual>();
}

typedef _c_TWDataCreateWithBytes = ffi.Pointer<ffi.Void> Function(
  ffi.Pointer<ffi.Int32> bytes,
  ffi.Int32 size,
);

typedef _dart_TWDataCreateWithBytes = ffi.Pointer<ffi.Void> Function(
  ffi.Pointer<ffi.Int32> bytes,
  int size,
);

typedef _c_TWDataCreateWithSize = ffi.Pointer<ffi.Void> Function(
  ffi.Int32 size,
);

typedef _dart_TWDataCreateWithSize = ffi.Pointer<ffi.Void> Function(
  int size,
);

typedef _c_TWDataCreateWithData = ffi.Pointer<ffi.Void> Function(
  ffi.Pointer<ffi.Void> data,
);

typedef _dart_TWDataCreateWithData = ffi.Pointer<ffi.Void> Function(
  ffi.Pointer<ffi.Void> data,
);

typedef _c_TWDataCreateWithHexString = ffi.Pointer<ffi.Void> Function(
  ffi.Pointer<ffi.Int32> hex,
);

typedef _dart_TWDataCreateWithHexString = ffi.Pointer<ffi.Void> Function(
  ffi.Pointer<ffi.Int32> hex,
);

typedef _c_TWDataSize = ffi.Int32 Function(
  ffi.Pointer<ffi.Void> data,
);

typedef _dart_TWDataSize = int Function(
  ffi.Pointer<ffi.Void> data,
);

typedef _c_TWDataBytes = ffi.Pointer<ffi.Int32> Function(
  ffi.Pointer<ffi.Void> data,
);

typedef _dart_TWDataBytes = ffi.Pointer<ffi.Int32> Function(
  ffi.Pointer<ffi.Void> data,
);

typedef _c_TWDataGet = ffi.Int32 Function(
  ffi.Pointer<ffi.Void> data,
  ffi.Int32 index,
);

typedef _dart_TWDataGet = int Function(
  ffi.Pointer<ffi.Void> data,
  int index,
);

typedef _c_TWDataSet = ffi.Void Function(
  ffi.Pointer<ffi.Void> data,
  ffi.Int32 index,
  ffi.Int32 byte,
);

typedef _dart_TWDataSet = void Function(
  ffi.Pointer<ffi.Void> data,
  int index,
  int byte,
);

typedef _c_TWDataCopyBytes = ffi.Void Function(
  ffi.Pointer<ffi.Void> data,
  ffi.Int32 start,
  ffi.Int32 size,
  ffi.Pointer<ffi.Int32> output,
);

typedef _dart_TWDataCopyBytes = void Function(
  ffi.Pointer<ffi.Void> data,
  int start,
  int size,
  ffi.Pointer<ffi.Int32> output,
);

typedef _c_TWDataReplaceBytes = ffi.Void Function(
  ffi.Pointer<ffi.Void> data,
  ffi.Int32 start,
  ffi.Int32 size,
  ffi.Pointer<ffi.Int32> bytes,
);

typedef _dart_TWDataReplaceBytes = void Function(
  ffi.Pointer<ffi.Void> data,
  int start,
  int size,
  ffi.Pointer<ffi.Int32> bytes,
);

typedef _c_TWDataAppendBytes = ffi.Void Function(
  ffi.Pointer<ffi.Void> data,
  ffi.Pointer<ffi.Int32> bytes,
  ffi.Int32 size,
);

typedef _dart_TWDataAppendBytes = void Function(
  ffi.Pointer<ffi.Void> data,
  ffi.Pointer<ffi.Int32> bytes,
  int size,
);

typedef _c_TWDataAppendByte = ffi.Void Function(
  ffi.Pointer<ffi.Void> data,
  ffi.Int32 byte,
);

typedef _dart_TWDataAppendByte = void Function(
  ffi.Pointer<ffi.Void> data,
  int byte,
);

typedef _c_TWDataAppendData = ffi.Void Function(
  ffi.Pointer<ffi.Void> data,
  ffi.Pointer<ffi.Void> append,
);

typedef _dart_TWDataAppendData = void Function(
  ffi.Pointer<ffi.Void> data,
  ffi.Pointer<ffi.Void> append,
);

typedef _c_TWDataReverse = ffi.Void Function(
  ffi.Pointer<ffi.Void> data,
);

typedef _dart_TWDataReverse = void Function(
  ffi.Pointer<ffi.Void> data,
);

typedef _c_TWDataReset = ffi.Void Function(
  ffi.Pointer<ffi.Void> data,
);

typedef _dart_TWDataReset = void Function(
  ffi.Pointer<ffi.Void> data,
);

typedef _c_TWDataDelete = ffi.Void Function(
  ffi.Pointer<ffi.Void> data,
);

typedef _dart_TWDataDelete = void Function(
  ffi.Pointer<ffi.Void> data,
);

typedef _c_TWDataEqual = ffi.Int32 Function(
  ffi.Pointer<ffi.Void> lhs,
  ffi.Pointer<ffi.Void> rhs,
);

typedef _dart_TWDataEqual = int Function(
  ffi.Pointer<ffi.Void> lhs,
  ffi.Pointer<ffi.Void> rhs,
);
