// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// trust wallet core
class TWFIOAccount_1 {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  TWFIOAccount_1(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  TWFIOAccount_1.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// Represents a FIO Account name
  late final ffi.Pointer<ffi.Int32> _TW_EXPORT_CLASS =
      _lookup<ffi.Int32>('TW_EXPORT_CLASS');

  int get TW_EXPORT_CLASS => _TW_EXPORT_CLASS.value;

  set TW_EXPORT_CLASS(int value) => _TW_EXPORT_CLASS.value = value;

  ffi.Pointer<ffi.Int32> TWFIOAccountCreateWithString(
    ffi.Pointer<ffi.Int32> string,
  ) {
    return _TWFIOAccountCreateWithString(
      string,
    );
  }

  late final _TWFIOAccountCreateWithString_ptr =
      _lookup<ffi.NativeFunction<_c_TWFIOAccountCreateWithString>>(
          'TWFIOAccountCreateWithString');
  late final _dart_TWFIOAccountCreateWithString _TWFIOAccountCreateWithString =
      _TWFIOAccountCreateWithString_ptr.asFunction<
          _dart_TWFIOAccountCreateWithString>();

  int TWFIOAccountDelete(
    ffi.Pointer<TWFIOAccount> account,
  ) {
    return _TWFIOAccountDelete(
      account,
    );
  }

  late final _TWFIOAccountDelete_ptr =
      _lookup<ffi.NativeFunction<_c_TWFIOAccountDelete>>('TWFIOAccountDelete');
  late final _dart_TWFIOAccountDelete _TWFIOAccountDelete =
      _TWFIOAccountDelete_ptr.asFunction<_dart_TWFIOAccountDelete>();

  /// Returns the short account string representation.
  late final ffi.Pointer<ffi.Int32> _TWString = _lookup<ffi.Int32>('TWString');

  int get TWString => _TWString.value;

  set TWString(int value) => _TWString.value = value;
}

class TWFIOAccount extends ffi.Opaque {}

typedef _c_TWFIOAccountCreateWithString = ffi.Pointer<ffi.Int32> Function(
  ffi.Pointer<ffi.Int32> string,
);

typedef _dart_TWFIOAccountCreateWithString = ffi.Pointer<ffi.Int32> Function(
  ffi.Pointer<ffi.Int32> string,
);

typedef _c_TWFIOAccountDelete = ffi.Int32 Function(
  ffi.Pointer<TWFIOAccount> account,
);

typedef _dart_TWFIOAccountDelete = int Function(
  ffi.Pointer<TWFIOAccount> account,
);
