// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// trust wallet core
class TWHash_1 {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  TWHash_1(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  TWHash_1.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  late final ffi.Pointer<ffi.Int32> _TW_EXPORT_STRUCT =
      _lookup<ffi.Int32>('TW_EXPORT_STRUCT');

  int get TW_EXPORT_STRUCT => _TW_EXPORT_STRUCT.value;

  set TW_EXPORT_STRUCT(int value) => _TW_EXPORT_STRUCT.value = value;

  late final ffi.Pointer<ffi.Int32> _TWHashSHA1Length =
      _lookup<ffi.Int32>('TWHashSHA1Length');

  int get TWHashSHA1Length => _TWHashSHA1Length.value;

  set TWHashSHA1Length(int value) => _TWHashSHA1Length.value = value;

  late final ffi.Pointer<ffi.Int32> _TWHashSHA256Length =
      _lookup<ffi.Int32>('TWHashSHA256Length');

  int get TWHashSHA256Length => _TWHashSHA256Length.value;

  set TWHashSHA256Length(int value) => _TWHashSHA256Length.value = value;

  late final ffi.Pointer<ffi.Int32> _TWHashSHA512Length =
      _lookup<ffi.Int32>('TWHashSHA512Length');

  int get TWHashSHA512Length => _TWHashSHA512Length.value;

  set TWHashSHA512Length(int value) => _TWHashSHA512Length.value = value;

  late final ffi.Pointer<ffi.Int32> _TWHashRipemdLength =
      _lookup<ffi.Int32>('TWHashRipemdLength');

  int get TWHashRipemdLength => _TWHashRipemdLength.value;

  set TWHashRipemdLength(int value) => _TWHashRipemdLength.value = value;

  /// Computes the SHA1 of a block of data.
  late final ffi.Pointer<ffi.Int32> _TWData = _lookup<ffi.Int32>('TWData');

  int get TWData => _TWData.value;

  set TWData(int value) => _TWData.value = value;
}

class TWHash extends ffi.Struct {
  @ffi.Int32()
  external int unused;
}
