// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// trust wallet core
class TWNEARAccount_1 {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  TWNEARAccount_1(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  TWNEARAccount_1.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// Represents a NEAR Account name
  late final ffi.Pointer<ffi.Int32> _TW_EXPORT_CLASS =
      _lookup<ffi.Int32>('TW_EXPORT_CLASS');

  int get TW_EXPORT_CLASS => _TW_EXPORT_CLASS.value;

  set TW_EXPORT_CLASS(int value) => _TW_EXPORT_CLASS.value = value;

  ffi.Pointer<ffi.Int32> TWNEARAccountCreateWithString(
    ffi.Pointer<ffi.Int32> string,
  ) {
    return _TWNEARAccountCreateWithString(
      string,
    );
  }

  late final _TWNEARAccountCreateWithString_ptr =
      _lookup<ffi.NativeFunction<_c_TWNEARAccountCreateWithString>>(
          'TWNEARAccountCreateWithString');
  late final _dart_TWNEARAccountCreateWithString
      _TWNEARAccountCreateWithString = _TWNEARAccountCreateWithString_ptr
          .asFunction<_dart_TWNEARAccountCreateWithString>();

  int TWNEARAccountDelete(
    ffi.Pointer<TWNEARAccount> account,
  ) {
    return _TWNEARAccountDelete(
      account,
    );
  }

  late final _TWNEARAccountDelete_ptr =
      _lookup<ffi.NativeFunction<_c_TWNEARAccountDelete>>(
          'TWNEARAccountDelete');
  late final _dart_TWNEARAccountDelete _TWNEARAccountDelete =
      _TWNEARAccountDelete_ptr.asFunction<_dart_TWNEARAccountDelete>();

  /// Returns the user friendly string representation.
  late final ffi.Pointer<ffi.Int32> _TWString = _lookup<ffi.Int32>('TWString');

  int get TWString => _TWString.value;

  set TWString(int value) => _TWString.value = value;
}

class TWNEARAccount extends ffi.Opaque {}

typedef _c_TWNEARAccountCreateWithString = ffi.Pointer<ffi.Int32> Function(
  ffi.Pointer<ffi.Int32> string,
);

typedef _dart_TWNEARAccountCreateWithString = ffi.Pointer<ffi.Int32> Function(
  ffi.Pointer<ffi.Int32> string,
);

typedef _c_TWNEARAccountDelete = ffi.Int32 Function(
  ffi.Pointer<TWNEARAccount> account,
);

typedef _dart_TWNEARAccountDelete = int Function(
  ffi.Pointer<TWNEARAccount> account,
);
