// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// trust wallet core
class TWSolanaAddress_1 {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  TWSolanaAddress_1(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  TWSolanaAddress_1.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  late final ffi.Pointer<ffi.Int32> _TW_EXPORT_CLASS =
      _lookup<ffi.Int32>('TW_EXPORT_CLASS');

  int get TW_EXPORT_CLASS => _TW_EXPORT_CLASS.value;

  set TW_EXPORT_CLASS(int value) => _TW_EXPORT_CLASS.value = value;

  /// Creates an address from a string representaion.
  ffi.Pointer<ffi.Int32> TWSolanaAddressCreateWithString(
    ffi.Pointer<ffi.Int32> string,
  ) {
    return _TWSolanaAddressCreateWithString(
      string,
    );
  }

  late final _TWSolanaAddressCreateWithString_ptr =
      _lookup<ffi.NativeFunction<_c_TWSolanaAddressCreateWithString>>(
          'TWSolanaAddressCreateWithString');
  late final _dart_TWSolanaAddressCreateWithString
      _TWSolanaAddressCreateWithString = _TWSolanaAddressCreateWithString_ptr
          .asFunction<_dart_TWSolanaAddressCreateWithString>();

  int TWSolanaAddressDelete(
    ffi.Pointer<TWSolanaAddress> address,
  ) {
    return _TWSolanaAddressDelete(
      address,
    );
  }

  late final _TWSolanaAddressDelete_ptr =
      _lookup<ffi.NativeFunction<_c_TWSolanaAddressDelete>>(
          'TWSolanaAddressDelete');
  late final _dart_TWSolanaAddressDelete _TWSolanaAddressDelete =
      _TWSolanaAddressDelete_ptr.asFunction<_dart_TWSolanaAddressDelete>();

  /// Derive default token address for token
  late final ffi.Pointer<ffi.Int32> _TWString = _lookup<ffi.Int32>('TWString');

  int get TWString => _TWString.value;

  set TWString(int value) => _TWString.value = value;
}

class TWSolanaAddress extends ffi.Opaque {}

typedef _c_TWSolanaAddressCreateWithString = ffi.Pointer<ffi.Int32> Function(
  ffi.Pointer<ffi.Int32> string,
);

typedef _dart_TWSolanaAddressCreateWithString = ffi.Pointer<ffi.Int32> Function(
  ffi.Pointer<ffi.Int32> string,
);

typedef _c_TWSolanaAddressDelete = ffi.Int32 Function(
  ffi.Pointer<TWSolanaAddress> address,
);

typedef _dart_TWSolanaAddressDelete = int Function(
  ffi.Pointer<TWSolanaAddress> address,
);
