// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

class TWStellarPassphrase {
  static const int TWStellarPassphraseStellar = 0;   /* "Public Global Stellar Network ; September 2015" */
  static const int TWStellarPassphraseKin     = 1;    /* "Kin Mainnet ; December 2018" */
  static const String TWStellarPassphrase_Stellar = "Public Global Stellar Network ; September 2015";
  static const String TWStellarPassphrase_Kin = "Kin Mainnet ; December 2018";
}
